alter table ONLINESTORE_ONLINE_ORDER add constraint FK_ONLINESTORE_ONLINE_ORDER_ON_BUYER foreign key (BUYER_ID) references ONLINESTORE_BUYER(ID);
create index IDX_ONLINESTORE_ONLINE_ORDER_ON_BUYER on ONLINESTORE_ONLINE_ORDER (BUYER_ID);
