alter table ONLINESTORE_LEGAL_PERSON add constraint FK_ONLINESTORE_LEGAL_PERSON_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_ONLINESTORE_LEGAL_PERSON_ON_USER on ONLINESTORE_LEGAL_PERSON (USER_ID);
