alter table ONLINESTORE_PRIVATE_PERSON add constraint FK_ONLINESTORE_PRIVATE_PERSON_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_ONLINESTORE_PRIVATE_PERSON_ON_USER on ONLINESTORE_PRIVATE_PERSON (USER_ID);
