-- begin ONLINESTORE_ONLINE_ORDER
alter table ONLINESTORE_ONLINE_ORDER add constraint FK_ONLINESTORE_ONLINE_ORDER_ON_BUYER foreign key (BUYER_ID) references ONLINESTORE_BUYER(ID)^
create index IDX_ONLINESTORE_ONLINE_ORDER_ON_BUYER on ONLINESTORE_ONLINE_ORDER (BUYER_ID)^
-- end ONLINESTORE_ONLINE_ORDER
-- begin SEC_USER
alter table SEC_USER add constraint FK_SEC_USER_ON_BUYER foreign key (BUYER_ID) references ONLINESTORE_BUYER(ID)^
create index IDX_SEC_USER_ON_BUYER on SEC_USER (BUYER_ID)^
-- end SEC_USER
