-- begin ONLINESTORE_ONLINE_ORDER
alter table ONLINESTORE_ONLINE_ORDER add constraint FK_ONLINESTORE_ONLINE_ORDER_ON_BUYER foreign key (BUYER_ID) references ONLINESTORE_BUYER(ID)^
create index IDX_ONLINESTORE_ONLINE_ORDER_ON_BUYER on ONLINESTORE_ONLINE_ORDER (BUYER_ID)^
-- end ONLINESTORE_ONLINE_ORDER
-- begin ONLINESTORE_PRIVATE_PERSON
alter table ONLINESTORE_PRIVATE_PERSON add constraint FK_ONLINESTORE_PRIVATE_PERSON_ON_ID foreign key (ID) references ONLINESTORE_BUYER(ID) on delete CASCADE^
-- end ONLINESTORE_PRIVATE_PERSON
-- begin ONLINESTORE_LEGAL_PERSON
alter table ONLINESTORE_LEGAL_PERSON add constraint FK_ONLINESTORE_LEGAL_PERSON_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
alter table ONLINESTORE_LEGAL_PERSON add constraint FK_ONLINESTORE_LEGAL_PERSON_ON_ID foreign key (ID) references ONLINESTORE_BUYER(ID) on delete CASCADE^
create index IDX_ONLINESTORE_LEGAL_PERSON_ON_USER on ONLINESTORE_LEGAL_PERSON (USER_ID)^
-- end ONLINESTORE_LEGAL_PERSON
-- begin SEC_USER
alter table SEC_USER add constraint FK_SEC_USER_ON_BUYER foreign key (BUYER_ID) references ONLINESTORE_BUYER(ID)^
create index IDX_SEC_USER_ON_BUYER on SEC_USER (BUYER_ID)^
-- end SEC_USER
-- begin ONLINESTORE_BUYER
alter table ONLINESTORE_BUYER add constraint FK_ONLINESTORE_BUYER_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_ONLINESTORE_BUYER_ON_USER on ONLINESTORE_BUYER (USER_ID)^
-- end ONLINESTORE_BUYER
